### ISSUE TITLE
Fuzzing

### ISSUE THREAD

**Issue by theHamsta** [stsewd/tree-sitter-rst#2]
Fuzzing is a good way to detect problems with your parser when you are using a custom `scanner.c`. See instructions here: https://github.com/ikatyang/tree-sitter-markdown/issues/14

```
❯ ./out/rst_fuzzer 
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2976557887
INFO: Loaded 1 modules   (21960 inline 8-bit counters): 21960 [0x7fe5f0, 0x803bb8), 
INFO: Loaded 1 PC tables (21960 PCs): 21960 [0x803bb8,0x859838), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
test/fixtures/grammars/rst/src/tree_sitter_rst/scanner.c:88:10: runtime error: null pointer passed as argument 1, which is declared to never be null
/usr/include/string.h:44:28: note: nonnull attribute specified here
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior test/fixtures/grammars/rst/src/tree_sitter_rst/scanner.c:88:10 in 
lib/src/lexer.c:76:55: runtime error: applying zero offset to null pointer
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior lib/src/lexer.c:76:55 in 
INFO: A corpus is not provided, starting from an empty corpus
#2      INITED cov: 2709 ft: 2710 corp: 1/1b exec/s: 0 rss: 35Mb
        NEW_FUNC[1/70]: 0x55bed0 in is_start_char /home/stephan/projects/tree-sitter/test/fixtures/grammars/rst/src/tree_sitter_rst/chars.c:196
        NEW_FUNC[2/70]: 0x569e10 in parse_text /home/stephan/projects/tree-sitter/test/fixtures/grammars/rst/src/tree_sitter_rst/parser.c:1514
#3      NEW    cov: 4667 ft: 6706 corp: 2/2b lim: 4 exec/s: 0 rss: 36Mb L: 1/1 MS: 1 ChangeByte-
#4      NEW    cov: 4676 ft: 6783 corp: 3/4b lim: 4 exec/s: 0 rss: 36Mb L: 2/2 MS: 1 CopyPart-
#5      NEW    cov: 4680 ft: 7675 corp: 4/6b lim: 4 exec/s: 0 rss: 36Mb L: 2/2 MS: 1 CopyPart-
        NEW_FUNC[1/1]: 0x6e6340 in ts_subtree_repeat_depth (/home/stephan/projects/tree-sitter/out/rst_fuzzer+0x6e6340)
#8      NEW    cov: 4839 ft: 9105 corp: 5/8b lim: 4 exec/s: 0 rss: 36Mb L: 2/2 MS: 3 ChangeByte-CopyPart-InsertByte-
        NEW_FUNC[1/2]: 0x6776c0 in ts_subtree_is_error (/home/stephan/projects/tree-sitter/out/rst_fuzzer+0x6776c0)
        NEW_FUNC[2/2]: 0x69bda0 in ts_subtree_symbol (/home/stephan/projects/tree-sitter/out/rst_fuzzer+0x69bda0)
#9      NEW    cov: 4864 ft: 9310 corp: 6/10b lim: 4 exec/s: 0 rss: 36Mb L: 2/2 MS: 1 ChangeBit-
        NEW_FUNC[1/6]: 0x5c7360 in ts_subtree_total_bytes (/home/stephan/projects/tree-sitter/out/rst_fuzzer+0x5c7360)
        NEW_FUNC[2/6]: 0x5cafd0 in ts_subtree_total_size (/home/stephan/projects/tree-sitter/out/rst_fuzzer+0x5cafd0)
#11     NEW    cov: 4984 ft: 10767 corp: 7/12b lim: 4 exec/s: 0 rss: 37Mb L: 2/2 MS: 2 ChangeBinInt-ChangeBit-
        NEW_FUNC[1/1]: 0x69c790 in ts_realloc (/home/stephan/projects/tree-sitter/out/rst_fuzzer+0x69c790)
#15     NEW    cov: 5009 ft: 11307 corp: 8/15b lim: 4 exec/s: 0 rss: 37Mb L: 3/3 MS: 4 CrossOver-ChangeBit-ShuffleBytes-CrossOver-
        NEW_FUNC[1/2]: 0x567d30 in parse_inner_numeric_bullet /home/stephan/projects/tree-sitter/test/fixtures/grammars/rst/src/tree_sitter_rst/parser.c:367
        NEW_FUNC[2/2]: 0x56ba40 in parse_numeric_bullet /home/stephan/projects/tree-sitter/test/fixtures/grammars/rst/src/tree_sitter_rst/parser.c:346
#16     NEW    cov: 5072 ft: 11655 corp: 9/17b lim: 4 exec/s: 0 rss: 37Mb L: 2/3 MS: 1 InsertByte-
#18     NEW    cov: 5078 ft: 11662 corp: 10/19b lim: 4 exec/s: 0 rss: 37Mb L: 2/3 MS: 2 EraseBytes-ChangeBit-
#19     NEW    cov: 5078 ft: 11668 corp: 11/20b lim: 4 exec/s: 0 rss: 37Mb L: 1/3 MS: 1 EraseBytes-
#23     NEW    cov: 5090 ft: 11680 corp: 12/22b lim: 4 exec/s: 0 rss: 37Mb L: 2/3 MS: 4 CrossOver-ShuffleBytes-ChangeByte-ChangeBinInt-
#26     NEW    cov: 5090 ft: 11736 corp: 13/25b lim: 4 exec/s: 0 rss: 38Mb L: 3/3 MS: 3 EraseBytes-ShuffleBytes-CrossOver-
        NEW_FUNC[1/5]: 0x579950 in rst_scanner_push /home/stephan/projects/tree-sitter/test/fixtures/grammars/rst/src/tree_sitter_rst/scanner.c:53
        NEW_FUNC[2/5]: 0x579c20 in rst_scanner_pop /home/stephan/projects/tree-sitter/test/fixtures/grammars/rst/src/tree_sitter_rst/scanner.c:61
#29     NEW    cov: 5321 ft: 12281 corp: 14/27b lim: 4 exec/s: 0 rss: 38Mb L: 2/3 MS: 3 EraseBytes-ChangeByte-ChangeBit-
#33     NEW    cov: 5326 ft: 12293 corp: 15/30b lim: 4 exec/s: 0 rss: 38Mb L: 3/3 MS: 4 CopyPart-CopyPart-EraseBytes-InsertByte-
#35     NEW    cov: 5339 ft: 12306 corp: 16/32b lim: 4 exec/s: 0 rss: 38Mb L: 2/3 MS: 2 ShuffleBytes-ChangeByte-
#36     NEW    cov: 5340 ft: 12307 corp: 17/34b lim: 4 exec/s: 0 rss: 38Mb L: 2/3 MS: 1 ChangeBinInt-
        NEW_FUNC[1/1]: 0x55ed90 in parse_overline /home/stephan/projects/tree-sitter/test/fixtures/grammars/rst/src/tree_sitter_rst/parser.c:64
#38     NEW    cov: 5373 ft: 12346 corp: 18/36b lim: 4 exec/s: 0 rss: 38Mb L: 2/3 MS: 2 EraseBytes-ChangeBinInt-
#39     NEW    cov: 5379 ft: 12353 corp: 19/38b lim: 4 exec/s: 0 rss: 38Mb L: 2/3 MS: 1 ChangeByte-
#41     NEW    cov: 5379 ft: 12355 corp: 20/39b lim: 4 exec/s: 0 rss: 38Mb L: 1/3 MS: 2 ShuffleBytes-EraseBytes-
#46     NEW    cov: 5381 ft: 12357 corp: 21/41b lim: 4 exec/s: 0 rss: 39Mb L: 2/3 MS: 5 CopyPart-ShuffleBytes-EraseBytes-ShuffleBytes-ChangeByte-
        NEW_FUNC[1/3]: 0x59f520 in ts_realloc (/home/stephan/projects/tree-sitter/out/rst_fuzzer+0x59f520)
        NEW_FUNC[2/3]: 0x677880 in pop_error_callback (/home/stephan/projects/tree-sitter/out/rst_fuzzer+0x677880)
#49     NEW    cov: 5563 ft: 13378 corp: 22/43b lim: 4 exec/s: 0 rss: 39Mb L: 2/3 MS: 3 CopyPart-CrossOver-ChangeByte-
#54     NEW    cov: 5563 ft: 13379 corp: 23/45b lim: 4 exec/s: 0 rss: 39Mb L: 2/3 MS: 5 ShuffleBytes-CrossOver-ChangeByte-ShuffleBytes-ShuffleBytes-
#58     NEW    cov: 5570 ft: 13407 corp: 24/48b lim: 4 exec/s: 0 rss: 39Mb L: 3/3 MS: 4 ChangeByte-CopyPart-ShuffleBytes-CrossOver-
#59     NEW    cov: 5590 ft: 13932 corp: 25/51b lim: 4 exec/s: 0 rss: 39Mb L: 3/3 MS: 1 CMP- DE: "\x13\x00"-
#61     NEW    cov: 5595 ft: 13938 corp: 26/54b lim: 4 exec/s: 0 rss: 39Mb L: 3/3 MS: 2 ChangeBit-ChangeBit-
#65     NEW    cov: 5595 ft: 13940 corp: 27/58b lim: 4 exec/s: 0 rss: 40Mb L: 4/4 MS: 4 InsertByte-ChangeByte-EraseBytes-InsertByte-
#66     NEW    cov: 5602 ft: 14085 corp: 28/61b lim: 4 exec/s: 0 rss: 40Mb L: 3/4 MS: 1 InsertByte-
#67     NEW    cov: 5602 ft: 14094 corp: 29/63b lim: 4 exec/s: 0 rss: 40Mb L: 2/4 MS: 1 ChangeByte-
        NEW_FUNC[1/1]: 0x5634a0 in parse_inner_inline_markup /home/stephan/projects/tree-sitter/test/fixtures/grammars/rst/src/tree_sitter_rst/parser.c:1065
#69     NEW    cov: 5633 ft: 14127 corp: 30/65b lim: 4 exec/s: 0 rss: 40Mb L: 2/4 MS: 2 EraseBytes-ChangeBit-
#71     NEW    cov: 5635 ft: 14679 corp: 31/68b lim: 4 exec/s: 0 rss: 40Mb L: 3/4 MS: 2 ShuffleBytes-PersAutoDict- DE: "\x13\x00"-
        NEW_FUNC[1/2]: 0x55c7b0 in is_internal_reference_char /home/stephan/projects/tree-sitter/test/fixtures/grammars/rst/src/tree_sitter_rst/chars.c:282
        NEW_FUNC[2/2]: 0x56bdf0 in parse_inner_standalone_hyperlink /home/stephan/projects/tree-sitter/test/fixtures/grammars/rst/src/tree_sitter_rst/parser.c:1282

=================================================================
==27362==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x52368d in malloc (/home/stephan/projects/tree-sitter/out/rst_fuzzer+0x52368d)
    #1 0x56bed8 in parse_inner_standalone_hyperlink /home/stephan/projects/tree-sitter/test/fixtures/grammars/rst/src/tree_sitter_rst/parser.c:1287:18
    #2 0x568b29 in parse_inner_numeric_bullet /home/stephan/projects/tree-sitter/test/fixtures/grammars/rst/src/tree_sitter_rst/parser.c:412:14
    #3 0x56bc7a in parse_numeric_bullet /home/stephan/projects/tree-sitter/test/fixtures/grammars/rst/src/tree_sitter_rst/parser.c:360:12
    #4 0x57b6a5 in rst_scanner_scan /home/stephan/projects/tree-sitter/test/fixtures/grammars/rst/src/tree_sitter_rst/scanner.c:165:12
    #5 0x57cd6e in tree_sitter_rst_external_scanner_scan /home/stephan/projects/tree-sitter/test/fixtures/grammars/rst/src/scanner.c:43:10
    #6 0x5a67f0 in ts_parser__lex (/home/stephan/projects/tree-sitter/out/rst_fuzzer+0x5a67f0)
    #7 0x594076 in ts_parser__advance (/home/stephan/projects/tree-sitter/out/rst_fuzzer+0x594076)
    #8 0x58e391 in ts_parser_parse (/home/stephan/projects/tree-sitter/out/rst_fuzzer+0x58e391)
    #9 0x59eba9 in ts_parser_parse_string_encoding (/home/stephan/projects/tree-sitter/out/rst_fuzzer+0x59eba9)
    #10 0x59e7d3 in ts_parser_parse_string (/home/stephan/projects/tree-sitter/out/rst_fuzzer+0x59e7d3)
    #11 0x558453 in LLVMFuzzerTestOneInput (/home/stephan/projects/tree-sitter/out/rst_fuzzer+0x558453)
    #12 0x45b831 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (/home/stephan/projects/tree-sitter/out/rst_fuzzer+0x45b831)
    #13 0x45ad7a in fuzzer::Fuzzer::RunOne(unsigned char const*, unsigned long, bool, fuzzer::InputInfo*, bool, bool*) (/home/stephan/projects/tree-sitter/out/rst_fuzzer+0x45ad7a)
    #14 0x45ca27 in fuzzer::Fuzzer::MutateAndTestOne() (/home/stephan/projects/tree-sitter/out/rst_fuzzer+0x45ca27)
    #15 0x45d5c5 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) (/home/stephan/projects/tree-sitter/out/rst_fuzzer+0x45d5c5)
    #16 0x44b76b in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (/home/stephan/projects/tree-sitter/out/rst_fuzzer+0x44b76b)
    #17 0x4750a2 in main (/home/stephan/projects/tree-sitter/out/rst_fuzzer+0x4750a2)
    #18 0x7f9ab47f7cb1 in __libc_start_main csu/../csu/libc-start.c:314:16

SUMMARY: AddressSanitizer: 8 byte(s) leaked in 1 allocation(s).
INFO: to ignore leaks on libFuzzer side use -detect_leaks=0.

MS: 1 ChangeBit-; base unit: 26776e135b7c21e4484e3a0abb629a51864fad48
0x4a,0x5a,
JZ
artifact_prefix='./'; Test unit written to ./leak-52ee862de32ba73e341b7c6be241b00d4a5c23ee
Base64: Slo=
```

**Comment by theHamsta** [comment]
I guess bfredl has already fixed this in upstream tree-sitter 
```
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior test/fixtures/grammars/rst/src/tree_sitter_rst/scanner.c:88:10 in 
lib/src/lexer.c:76:55: runtime error: applying zero offset to null pointer
```

**Comment by theHamsta** [comment]
When running without memory leaks: `-detect_leaks=0`
```

0x000000794664 is located 60 bytes to the left of global variable '<string literal>' defined in 'test/fixtures/grammars/rst/src/tree_sitter_rst/chars.c:418:5' (0x7946a0) of size 7
  '<string literal>' is ascii string 'mailto'
0x000000794664 is located 0 bytes to the right of global variable '<string literal>' defined in 'test/fixtures/grammars/rst/src/tree_sitter_rst/chars.c:417:5' (0x794660) of size 4
  '<string literal>' is ascii string 'ftp'
SUMMARY: AddressSanitizer: global-buffer-overflow (/home/stephan/projects/tree-sitter/out/rst_fuzzer+0x4be9eb) in MemcmpInterceptorCommon(void*, int (*)(void const*, void const*, unsigned long), void const*, void const*, unsigned long)
Shadow bytes around the buggy address:
  0x0000800ea870: 00 00 00 04 f9 f9 f9 f9 00 00 04 f9 f9 f9 f9 f9
  0x0000800ea880: 00 00 f9 f9 f9 f9 f9 f9 00 00 04 f9 f9 f9 f9 f9
  0x0000800ea890: 00 00 00 f9 f9 f9 f9 f9 00 00 00 04 f9 f9 f9 f9
  0x0000800ea8a0: 00 00 00 04 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x0000800ea8b0: 00 00 00 00 00 00 00 00 00 00 00 00 05 f9 f9 f9
=>0x0000800ea8c0: f9 f9 f9 f9 06 f9 f9 f9 f9 f9 f9 f9[04]f9 f9 f9
  0x0000800ea8d0: f9 f9 f9 f9 07 f9 f9 f9 f9 f9 f9 f9 07 f9 f9 f9
  0x0000800ea8e0: f9 f9 f9 f9 04 f9 f9 f9 f9 f9 f9 f9 00 00 00 00
  0x0000800ea8f0: 00 00 f9 f9 f9 f9 f9 f9 00 00 00 00 00 00 00 00
  0x0000800ea900: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0000800ea910: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==32376==ABORTING
MS: 2 PersAutoDict-PersAutoDict- DE: "\x1f\x00"-"DNDD"-; base unit: 468b68de792d7dec386b15fa0d7d26eae33ca74b
0x1b,0x0,0x41,0x44,0x4e,0x44,0x44,0x3a,
\x1b\x00ADNDD:
artifact_prefix='./'; Test unit written to ./crash-d925baf19dcb1aea830b3687907d6fa778872982
Base64: GwBBRE5ERDo=
```

**Comment by stsewd** [comment]
oops, somehow missed this, I'm not that familiar with fuzzing, but I'll check the instructions, thanks. There are some things that are expected to give errors https://github.com/stsewd/tree-sitter-rst/blob/aa61d0e2930de134089326973686ac547cca9e03/Makefile#L24-L31

**Comment by stsewd** [comment]
I've run the fuzzer, I think everything should be good now. I may create a dockerfile later to run it after each change.
